modLoader="javafml"
loaderVersion="[47,)"
license="MIT License https://github.com/McJtyMods/RFToolsBuilder/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/RFToolsBuilder/issues"
displayURL="http://github.com/McJtyMods/RFToolsBuilder/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="rftoolsbuilder"
version="${file.jarVersion}"
displayName="RFToolsBuilder"
#updateJSONURL="http://myurl.me/" #optional
description='''
Everything related to the builder
'''
[[dependencies.rftoolsbuilder]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rftoolsbuilder]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.20-8.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.rftoolsbuilder]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.20-5.0.0,)"
    ordering="AFTER"
    side="BOTH"