modLoader="javafml"
loaderVersion="[33,)"
license="MIT License https://github.com/McJtyMods/RFToolsBuilder/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/RFToolsBuilder/issues"
displayURL="http://github.com/McJtyMods/RFToolsBuilder/"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="McJty"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="rftoolsbuilder"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
displayName="RFToolsBuilder"
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Everything related to the builder
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.rftoolsbuilder]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.rftoolsbuilder]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rftoolsbuilder]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.15-4.0.9,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.rftoolsbuilder]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.15-1.0.9,)"
    ordering="AFTER"
    side="BOTH"